[WinEventLog://Application]
index = soc-automation
disabled = false

[WinEventLog://Security]
index = soc-automation
disabled = false

[WinEventLog://System]
index = soc-automation
disabled = false

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
index = soc-automation
disabled = false
renderXml = true
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational

[WinEventLog://Microsoft-Windows Defender/Operational]
index = soc-automation
disabled = false
source = XmlWinEventLog:Microsoft-Windows Defender/Operational
blacklist = 1151,1150,2000,1002,1001,1000

[WinEventLog://Microsoft-Windows-Powershell/Operational]
index = soc-automation
disabled = false
source = XmlWinEventLog:Microsoft-Windows-Powershell/Operational
blacklist = 4100,4105,4106,40961,40962,53504